version: "3"

services:
  db:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: woahbase/alpine-adminer
    restart: always
    ports:
      - 80:8080