version: "3"

services:
  db:
    image: clutteredcode/mongo-alpine
    restart: always
    environment:
      MONGO_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/data/db
    ports:
      - 27017:27017

  adminer:
    image: woahbase/alpine-adminer
    restart: always
    ports:
      - 80:8080
